steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - packages/portal/Dockerfile
      - -t
      - asia-northeast3-docker.pkg.dev/cso-ai/apps/portal:v7
      - .
images:
  - asia-northeast3-docker.pkg.dev/cso-ai/apps/portal:v7
options:
  machineType: E2_HIGHCPU_8
